
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "COMMA MAIS MENOS NUM PA PF POINT Sentence : MENOS Intervals POINT Sentence : MAIS Intervals POINT Signal : '+'  Signal : '-' Intervals : Interval RemainingIntervals RemainingIntervals : \n                           | Interval RemainingIntervals Interval : PA NUM COMMA NUM PF "
    
_lr_action_items = {'MENOS':([0,],[2,]),'MAIS':([0,],[3,]),'$end':([1,8,12,],[0,-1,-2,]),'PA':([2,3,5,9,16,],[6,6,6,6,-8,]),'POINT':([4,5,7,9,10,13,16,],[8,-6,12,-6,-5,-7,-8,]),'NUM':([6,14,],[11,15,]),'COMMA':([11,],[14,]),'PF':([15,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Sentence':([0,],[1,]),'Intervals':([2,3,],[4,7,]),'Interval':([2,3,5,9,],[5,5,9,9,]),'RemainingIntervals':([5,9,],[10,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Sentence","S'",1,None,None,None),
  ('Sentence -> MENOS Intervals POINT','Sentence',3,'p_Sentence_1','TPC1_sint.py',15),
  ('Sentence -> MAIS Intervals POINT','Sentence',3,'p_Sentence_2','TPC1_sint.py',26),
  ('Signal -> +','Signal',1,'p_SignalPos','TPC1_sint.py',37),
  ('Signal -> -','Signal',1,'p_SignalNeg','TPC1_sint.py',41),
  ('Intervals -> Interval RemainingIntervals','Intervals',2,'p_Intervals','TPC1_sint.py',45),
  ('RemainingIntervals -> <empty>','RemainingIntervals',0,'p_RemainingIntervals','TPC1_sint.py',49),
  ('RemainingIntervals -> Interval RemainingIntervals','RemainingIntervals',2,'p_RemainingIntervals','TPC1_sint.py',50),
  ('Interval -> PA NUM COMMA NUM PF','Interval',5,'p_Interval','TPC1_sint.py',57),
]
